name: paraiba_turismo
description: Aplicativo de turismo da Paraíba - Roteiros culturais e ecológicos

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI e Navegação
  cupertino_icons: ^1.0.2
  go_router: ^12.1.3
  
  # Estado e Dados
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # Imagens e Assets
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  
  # Utilitários
  intl: ^0.19.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  
  # Animações
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/